/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sells;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication2.function;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static sells.sells.pass;
import static sells.sells.url;
import static sells.sells.user;

/**
 *
 * @author DELL
 */
public class bill extends javax.swing.JFrame {
  public static String url = "jdbc:mysql://localhost:3306/prog63";
  public static String user = "root";           
  public static String pass =  "1234567q";
    /**
     * Creates new form sells
     */
    public bill() {
        initComponents();
        emp();
        cust();
        item();
        id();     
        function.tdesign(table);
//        scrollPane of table
        sp.setOpaque(false);
        sp.getViewport().setOpaque(false);
       
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JComboBox<>();
        t4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-48.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-minimize-48.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 50, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("العميل");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 30));

        t4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("الاصناف");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("الموظف");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 70, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("التاريخ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 30));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 30));

        jLabel6.setText("رقم الفاتورة");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "السعر", "المخزن", "العدد", "الصنف"
            }
        ));
        sp.setViewportView(table);

        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 620, 200));

        jLabel10.setBackground(new java.awt.Color(153, 153, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("اضافة");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, 30));

        jLabel11.setBackground(new java.awt.Color(153, 153, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("تم");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, 30));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
          private void emp (){
             String sql = "select * from emp;";
            DefaultTableModel model = (DefaultTableModel)table.getModel();    
           try(Connection con = DriverManager.getConnection(url, user,pass)){
              System.out.println("done");
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){t1.addItem(rs.getString("name"));}
              } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
           
}
       private void cust (){
             String sql = "select * from cust;";
            DefaultTableModel model = (DefaultTableModel)table.getModel();    
           try(Connection con = DriverManager.getConnection(url, user,pass)){
              System.out.println("done");
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){t2.addItem(rs.getString("name"));}
              } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
           
}
          private void item (){
             String sql = "select * from item;";
            DefaultTableModel model = (DefaultTableModel)table.getModel();    
           try(Connection con = DriverManager.getConnection(url, user,pass)){
              System.out.println("done");
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){t4.addItem(rs.getString("name"));}
              } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
           
}
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel)table.getModel();
               int total=0;
             String bill = "insert into bill (idbill,emp,cust,date) values (?,?,?,?);";
             String sitems = "insert into sitems (idsitem,name,count,price) values (?,?,?,?);";
             String ucust = "update cust set debt=debt+? where name='"+t2.getSelectedItem().toString()+"';";
             String uitem = "update item set count=count-? where name=?;";
           try(Connection con = DriverManager.getConnection(url, user,pass)){
             
              PreparedStatement pstbill = con.prepareStatement(bill);
              pstbill.setInt(1,Integer.parseInt(id.getText()));
              pstbill.setString(2,t1.getSelectedItem().toString());
              pstbill.setString(3,t2.getSelectedItem().toString());
              pstbill.setString(4, t3.getText());
              pstbill.execute();
              
              PreparedStatement pstitems = con.prepareStatement(sitems);
              PreparedStatement pst = con.prepareStatement(uitem);
              PreparedStatement st = con.prepareStatement(ucust);
              
              for (int i=0;i<table.getRowCount();i++){
              pstitems.setInt(1, Integer.parseInt(id.getText()));
              pstitems.setString(2, model.getValueAt(i,3).toString());
              pstitems.setInt(3, Integer.parseInt(model.getValueAt(i,2).toString()));
              pstitems.setInt(4, Integer.parseInt(model.getValueAt(i,0).toString()));
              pstitems.execute();
              //to update count in store(table: item)
              pst.setInt(1, Integer.parseInt(model.getValueAt(i,2).toString()));
              pst.setString(2, model.getValueAt(i,3).toString());
              pst.execute();
              
              total = total + (Integer.parseInt(model.getValueAt(i,2).toString()) * Integer.parseInt(model.getValueAt(i,0).toString()));
             
              }
              st.setInt(1, total);
              st.execute();
              
              JOptionPane.showMessageDialog(this, "تمت الاضاقة");
              
//              clear
              t3.setText("");
              t5.setText("");
              id.setText("");
              model.setRowCount(0);
              id();
             } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jLabel11MouseClicked
private void id (){
             String sql = "select idbill from bill order by idbill desc limit 1;";
              
           try(Connection con = DriverManager.getConnection(url, user,pass)){
              
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){id.setText(Integer.toString(rs.getInt("idbill")+1));
              }
              } catch (SQLException ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        }
           
}
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
  String sql = "select * from item where name='"+t4.getSelectedItem()+"';";
        DefaultTableModel model = (DefaultTableModel)table.getModel();    
      try(Connection con = DriverManager.getConnection(url, user,pass)){
              
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){
                 model.addRow(new Object[]{rs.getInt("price"),rs.getInt("count"),t5.getText(),rs.getString("name")});
              
              }
              } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jLabel10MouseClicked
public static void loadingbill (){
   String sqlbill = "select *,date_format(date,'%d/%m/%Y')as ddate from bill where idbill="+id.getText()+"  ;";
   String sqlsitems = "select * from sitems where idsitem="+id.getText()+" ;";
            DefaultTableModel model = (DefaultTableModel)table.getModel();    
           try(Connection con = DriverManager.getConnection(url, user,pass)){
              
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sqlbill);
              while (rs.next()){
             t3.setText(rs.getString("ddate"));
             t2.setSelectedItem(rs.getString("cust"));
             t1.setSelectedItem(rs.getString("emp"));
              }
              rs = st.executeQuery(sqlsitems);
               while (rs.next()){
             model.addRow(new Object[]{rs.getString("price"),rs.getString("count"),rs.getString("name")});
              
              }
              } catch (SQLException ex) {
            Logger.getLogger(item.class.getName()).log(Level.SEVERE, null, ex);
        }
           


}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane sp;
    public static javax.swing.JComboBox<String> t1;
    public static javax.swing.JComboBox<String> t2;
    public static javax.swing.JTextField t3;
    private javax.swing.JComboBox<String> t4;
    private javax.swing.JTextField t5;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
